"""
============================================================
AALTO V3 - Siamese BiLSTM Behavioral Authentication
============================================================

Research objective:
    Learn a behavioral representation from keystroke sequences
    using a Siamese BiLSTM architecture.

Input:
    50 timesteps x 16 behavioral features

Pair labels:
    1 = same participant / genuine pair
    0 = different participants / impostor pair

Data:
    processed/siamese_bilstm_v3/

Pairs:
    pairs/train_pairs_v3.csv
    pairs/validation_pairs_v3.csv
    pairs/test_pairs_v3.csv

Normalization:
    TRAIN-ONLY scaler generated by normalization audit.

Important research controls:
    - Participant-level train/validation/test split
    - Shared Siamese encoder weights
    - Test set NEVER used for training
    - Test set NEVER used for threshold selection
    - Validation used for model selection
    - Validation used for threshold selection
    - Test used only for final evaluation
    - Random seed = 42
"""

import os
import json
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42

BASE_DIR = Path("processed/siamese_bilstm_v3")

TRAIN_PAIR_FILE = (
    BASE_DIR / "pairs" / "train_pairs_v3.csv"
)

VALIDATION_PAIR_FILE = (
    BASE_DIR / "pairs" / "validation_pairs_v3.csv"
)

TEST_PAIR_FILE = (
    BASE_DIR / "pairs" / "test_pairs_v3.csv"
)

SCALER_FILE = (
    BASE_DIR
    / "reports"
    / "normalization_audit"
    / "train_only_scaler_v3.npz"
)

OUTPUT_DIR = (
    BASE_DIR / "model_training_v3"
)

CHECKPOINT_DIR = (
    OUTPUT_DIR / "checkpoints"
)

REPORT_DIR = (
    OUTPUT_DIR / "reports"
)


# ============================================================
# MODEL PARAMETERS
# ============================================================

SEQUENCE_LENGTH = 50
FEATURE_COUNT = 16

LSTM_HIDDEN_SIZE = 128

LSTM_LAYERS = 2

EMBEDDING_SIZE = 64

DROPOUT = 0.30

MARGIN = 1.0

BATCH_SIZE = 256

EPOCHS = 50

LEARNING_RATE = 1e-3

WEIGHT_DECAY = 1e-5

PATIENCE = 7

NUM_WORKERS = 0


# ============================================================
# DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


# ============================================================
# REPRODUCIBILITY
# ============================================================

def set_seed(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Deterministic behavior.
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ============================================================
# DIRECTORIES
# ============================================================

def create_directories():

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    CHECKPOINT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )


# ============================================================
# SCALER LOADING
# ============================================================

def load_train_scaler():

    if not SCALER_FILE.exists():

        raise FileNotFoundError(
            f"\nTRAIN-ONLY SCALER NOT FOUND:\n"
            f"{SCALER_FILE}\n\n"
            f"Do NOT train without the train-only scaler."
        )

    scaler = np.load(
        SCALER_FILE,
        allow_pickle=False
    )

    print()
    print("=" * 70)
    print("TRAIN-ONLY NORMALIZATION SCALER")
    print("=" * 70)

    print(
        "Scaler file:",
        SCALER_FILE
    )

    print(
        "Available arrays:",
        list(scaler.keys())
    )

    # --------------------------------------------------------
    # Try common naming conventions.
    # --------------------------------------------------------

    mean_keys = [
        "mean",
        "means",
        "feature_mean",
        "feature_means",
        "train_mean",
        "train_means",
    ]

    std_keys = [
        "std",
        "stds",
        "feature_std",
        "feature_stds",
        "train_std",
        "train_stds",
    ]

    mean = None
    std = None

    for key in mean_keys:

        if key in scaler:

            mean = scaler[key]
            break

    for key in std_keys:

        if key in scaler:

            std = scaler[key]
            break

    if mean is None or std is None:

        raise RuntimeError(
            "\nCould not identify mean/std arrays in the "
            "train-only scaler.\n\n"
            f"Available arrays: {list(scaler.keys())}\n\n"
            "Inspect the scaler file before training."
        )

    mean = np.asarray(
        mean,
        dtype=np.float32
    ).reshape(-1)

    std = np.asarray(
        std,
        dtype=np.float32
    ).reshape(-1)

    if len(mean) != FEATURE_COUNT:

        raise ValueError(
            f"Scaler mean has {len(mean)} features; "
            f"expected {FEATURE_COUNT}."
        )

    if len(std) != FEATURE_COUNT:

        raise ValueError(
            f"Scaler std has {len(std)} features; "
            f"expected {FEATURE_COUNT}."
        )

    if not np.all(np.isfinite(mean)):

        raise ValueError(
            "Scaler mean contains NaN/Inf."
        )

    if not np.all(np.isfinite(std)):

        raise ValueError(
            "Scaler std contains NaN/Inf."
        )

    if np.any(std <= 0):

        raise ValueError(
            "Scaler contains zero/negative standard deviation."
        )

    print(
        "Features:",
        len(mean)
    )

    print(
        "Scaler source: TRAIN ONLY"
    )

    print(
        "Validation used for scaler: NO"
    )

    print(
        "Test used for scaler: NO"
    )

    return mean, std


# ============================================================
# NPZ LOADER
# ============================================================

def load_npz_sequence(path):

    if not path.exists():

        raise FileNotFoundError(
            f"Sequence file not found:\n{path}"
        )

    data = np.load(
        path,
        allow_pickle=False
    )

    keys = list(data.keys())

    # --------------------------------------------------------
    # Prefer common sequence-array names.
    # --------------------------------------------------------

    preferred_keys = [
        "X",
        "x",
        "sequence",
        "features",
        "data",
        "arr_0",
    ]

    array = None

    for key in preferred_keys:

        if key in data:

            candidate = data[key]

            if isinstance(candidate, np.ndarray):

                array = candidate
                break

    # --------------------------------------------------------
    # If no preferred key, search for 2D array.
    # --------------------------------------------------------

    if array is None:

        candidates = []

        for key in keys:

            candidate = data[key]

            if (
                isinstance(candidate, np.ndarray)
                and candidate.ndim == 2
            ):

                candidates.append(candidate)

        if len(candidates) == 1:

            array = candidates[0]

        elif len(candidates) > 1:

            raise ValueError(
                f"Multiple possible sequence arrays in {path}: "
                f"{keys}"
            )

    if array is None:

        raise ValueError(
            f"Could not identify sequence array in:\n"
            f"{path}\n"
            f"Available keys: {keys}"
        )

    array = np.asarray(
        array,
        dtype=np.float32
    )

    # --------------------------------------------------------
    # Shape validation
    # --------------------------------------------------------

    if array.shape != (
        SEQUENCE_LENGTH,
        FEATURE_COUNT
    ):

        raise ValueError(
            f"Invalid sequence shape in:\n"
            f"{path}\n"
            f"Expected: "
            f"({SEQUENCE_LENGTH}, {FEATURE_COUNT})\n"
            f"Got: {array.shape}"
        )

    if not np.all(np.isfinite(array)):

        raise ValueError(
            f"NaN/Inf detected in:\n{path}"
        )

    return array


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_sequence(
    sequence,
    mean,
    std
):

    sequence = (
        sequence - mean
    ) / std

    if not np.all(
        np.isfinite(sequence)
    ):

        raise ValueError(
            "Normalization produced NaN/Inf."
        )

    return sequence.astype(
        np.float32
    )


# ============================================================
# PAIR DATASET
# ============================================================

class SiamesePairDataset(Dataset):

    def __init__(
        self,
        pair_csv,
        mean,
        std,
    ):

        self.pairs = pd.read_csv(
            pair_csv
        )

        self.mean = mean
        self.std = std

        required_columns = [
            "pair_id",
            "sequence_1",
            "sequence_2",
            "participant_1",
            "participant_2",
            "label",
            "pair_type",
        ]

        missing = [
            c
            for c in required_columns
            if c not in self.pairs.columns
        ]

        if missing:

            raise ValueError(
                f"Missing pair columns: {missing}"
            )

        if len(self.pairs) == 0:

            raise ValueError(
                f"Empty pair file: {pair_csv}"
            )

        # ----------------------------------------------------
        # Validate labels before training.
        # ----------------------------------------------------

        for _, row in self.pairs.iterrows():

            label = int(row["label"])

            p1 = int(
                row["participant_1"]
            )

            p2 = int(
                row["participant_2"]
            )

            if label == 1 and p1 != p2:

                raise ValueError(
                    "Invalid positive pair detected."
                )

            if label == 0 and p1 == p2:

                raise ValueError(
                    "Invalid negative pair detected."
                )

        self.base_dir = BASE_DIR

    def __len__(self):

        return len(self.pairs)

    def __getitem__(self, index):

        row = self.pairs.iloc[index]

        path1 = (
            self.base_dir
            / row["sequence_1"]
        )

        path2 = (
            self.base_dir
            / row["sequence_2"]
        )

        x1 = load_npz_sequence(
            path1
        )

        x2 = load_npz_sequence(
            path2
        )

        x1 = normalize_sequence(
            x1,
            self.mean,
            self.std
        )

        x2 = normalize_sequence(
            x2,
            self.mean,
            self.std
        )

        label = np.float32(
            row["label"]
        )

        return (
            torch.from_numpy(x1),
            torch.from_numpy(x2),
            torch.tensor(
                label,
                dtype=torch.float32
            ),
        )


# ============================================================
# SIAMESE BiLSTM ENCODER
# ============================================================

class BiLSTMEncoder(nn.Module):

    def __init__(self):

        super().__init__()

        self.lstm = nn.LSTM(
            input_size=FEATURE_COUNT,
            hidden_size=LSTM_HIDDEN_SIZE,
            num_layers=LSTM_LAYERS,
            batch_first=True,
            bidirectional=True,
            dropout=DROPOUT
            if LSTM_LAYERS > 1
            else 0.0,
        )

        self.embedding = nn.Sequential(

            nn.Linear(
                LSTM_HIDDEN_SIZE * 2,
                128
            ),

            nn.ReLU(),

            nn.Dropout(
                DROPOUT
            ),

            nn.Linear(
                128,
                EMBEDDING_SIZE
            ),
        )

    def forward(self, x):

        output, _ = self.lstm(x)

        # Last timestep representation.
        last_output = output[:, -1, :]

        embedding = self.embedding(
            last_output
        )

        # L2 normalization makes the embedding
        # suitable for distance-based comparison.
        embedding = nn.functional.normalize(
            embedding,
            p=2,
            dim=1
        )

        return embedding


# ============================================================
# SIAMESE NETWORK
# ============================================================

class SiameseBiLSTM(nn.Module):

    def __init__(self):

        super().__init__()

        # IMPORTANT:
        #
        # There is ONE encoder object.
        #
        # Both sequences therefore use exactly
        # the same weights.

        self.encoder = BiLSTMEncoder()

    def forward(
        self,
        x1,
        x2
    ):

        embedding1 = self.encoder(
            x1
        )

        embedding2 = self.encoder(
            x2
        )

        distance = torch.norm(
            embedding1 - embedding2,
            p=2,
            dim=1
        )

        return (
            embedding1,
            embedding2,
            distance
        )


# ============================================================
# CONTRASTIVE LOSS
# ============================================================

class ContrastiveLoss(nn.Module):

    def __init__(
        self,
        margin=1.0
    ):

        super().__init__()

        self.margin = margin

    def forward(
        self,
        distance,
        label
    ):

        # label = 1:
        # same participant
        # minimize distance
        #
        # label = 0:
        # different participant
        # push distance beyond margin

        positive_loss = (
            label
            * torch.pow(distance, 2)
        )

        negative_loss = (
            (1 - label)
            * torch.pow(
                torch.clamp(
                    self.margin - distance,
                    min=0.0
                ),
                2
            )
        )

        loss = (
            positive_loss
            + negative_loss
        )

        return loss.mean()


# ============================================================
# METRICS
# ============================================================

def calculate_pair_metrics(
    distances,
    labels,
    threshold
):

    distances = np.asarray(
        distances
    )

    labels = np.asarray(
        labels
    )

    predictions = (
        distances <= threshold
    ).astype(int)

    genuine = (
        labels == 1
    )

    impostor = (
        labels == 0
    )

    tp = np.sum(
        predictions[genuine] == 1
    )

    fn = np.sum(
        predictions[genuine] == 0
    )

    fp = np.sum(
        predictions[impostor] == 1
    )

    tn = np.sum(
        predictions[impostor] == 0
    )

    tpr = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0.0
    )

    fpr = (
        fp / (fp + tn)
        if (fp + tn) > 0
        else 0.0
    )

    fnr = (
        fn / (tp + fn)
        if (tp + fn) > 0
        else 0.0
    )

    accuracy = (
        (tp + tn)
        /
        (tp + tn + fp + fn)
    )

    return {
        "threshold": float(threshold),
        "accuracy": float(accuracy),
        "tpr": float(tpr),
        "fpr": float(fpr),
        "fnr": float(fnr),
        "tp": int(tp),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
    }


# ============================================================
# FIND VALIDATION THRESHOLD
# ============================================================

def find_best_validation_threshold(
    distances,
    labels
):

    distances = np.asarray(
        distances
    )

    labels = np.asarray(
        labels
    )

    thresholds = np.linspace(
        distances.min(),
        distances.max(),
        501
    )

    best = None

    for threshold in thresholds:

        metrics = calculate_pair_metrics(
            distances,
            labels,
            threshold
        )

        if (
            best is None
            or metrics["accuracy"]
            > best["accuracy"]
        ):

            best = metrics

    return best


# ============================================================
# EER THRESHOLD
# ============================================================

def find_eer(
    distances,
    labels
):

    distances = np.asarray(
        distances
    )

    labels = np.asarray(
        labels
    )

    thresholds = np.linspace(
        distances.min(),
        distances.max(),
        2001
    )

    best = None

    for threshold in thresholds:

        metrics = calculate_pair_metrics(
            distances,
            labels,
            threshold
        )

        difference = abs(
            metrics["fpr"]
            - metrics["fnr"]
        )

        if (
            best is None
            or difference
            < best["difference"]
        ):

            best = {
                "threshold": float(
                    threshold
                ),
                "far": metrics["fpr"],
                "frr": metrics["fnr"],
                "difference": float(
                    difference
                ),
            }

    best["eer"] = (
        best["far"]
        + best["frr"]
    ) / 2.0

    return best


# ============================================================
# TRAIN ONE EPOCH
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion
):

    model.train()

    total_loss = 0.0

    total_samples = 0

    for x1, x2, labels in loader:

        x1 = x1.to(
            DEVICE,
            non_blocking=True
        )

        x2 = x2.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        _, _, distance = model(
            x1,
            x2
        )

        loss = criterion(
            distance,
            labels
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=5.0
        )

        optimizer.step()

        batch_size = (
            labels.size(0)
        )

        total_loss += (
            loss.item()
            * batch_size
        )

        total_samples += batch_size

    return (
        total_loss
        / total_samples
    )


# ============================================================
# EVALUATION
# ============================================================

def evaluate(
    model,
    loader,
    criterion,
    threshold=None
):

    model.eval()

    total_loss = 0.0

    total_samples = 0

    all_distances = []

    all_labels = []

    with torch.no_grad():

        for x1, x2, labels in loader:

            x1 = x1.to(
                DEVICE,
                non_blocking=True
            )

            x2 = x2.to(
                DEVICE,
                non_blocking=True
            )

            labels = labels.to(
                DEVICE,
                non_blocking=True
            )

            _, _, distance = model(
                x1,
                x2
            )

            loss = criterion(
                distance,
                labels
            )

            batch_size = (
                labels.size(0)
            )

            total_loss += (
                loss.item()
                * batch_size
            )

            total_samples += batch_size

            all_distances.extend(
                distance.cpu().numpy()
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

    mean_loss = (
        total_loss
        / total_samples
    )

    all_distances = np.asarray(
        all_distances
    )

    all_labels = np.asarray(
        all_labels
    ).astype(int)

    result = {
        "loss": float(mean_loss),
        "distances": all_distances,
        "labels": all_labels,
    }

    if threshold is not None:

        result["metrics"] = (
            calculate_pair_metrics(
                all_distances,
                all_labels,
                threshold
            )
        )

    return result


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    model,
    optimizer,
    epoch,
    validation_loss,
    path
):

    torch.save(
        {
            "epoch": epoch,
            "model_state_dict":
                model.state_dict(),
            "optimizer_state_dict":
                optimizer.state_dict(),
            "validation_loss":
                validation_loss,
            "config": {
                "sequence_length":
                    SEQUENCE_LENGTH,
                "feature_count":
                    FEATURE_COUNT,
                "lstm_hidden_size":
                    LSTM_HIDDEN_SIZE,
                "lstm_layers":
                    LSTM_LAYERS,
                "embedding_size":
                    EMBEDDING_SIZE,
                "margin":
                    MARGIN,
            },
            "seed": SEED,
        },
        path
    )


# ============================================================
# MAIN
# ============================================================

def main():

    set_seed(SEED)

    create_directories()

    start_time = time.time()

    print("=" * 70)
    print("AALTO V3 SIAMESE BiLSTM TRAINING")
    print("=" * 70)

    print()
    print(
        f"Device : {DEVICE}"
    )

    if torch.cuda.is_available():

        print(
            "GPU:",
            torch.cuda.get_device_name(0)
        )

    print()
    print("Sequence:")
    print(
        f"    {SEQUENCE_LENGTH} timesteps "
        f"x {FEATURE_COUNT} features"
    )

    print()
    print("Model:")
    print(
        f"    BiLSTM hidden size : "
        f"{LSTM_HIDDEN_SIZE}"
    )

    print(
        f"    LSTM layers       : "
        f"{LSTM_LAYERS}"
    )

    print(
        f"    Embedding size    : "
        f"{EMBEDDING_SIZE}"
    )

    print(
        f"    Margin            : "
        f"{MARGIN}"
    )

    print(
        f"    Batch size        : "
        f"{BATCH_SIZE}"
    )

    print(
        f"    Maximum epochs    : "
        f"{EPOCHS}"
    )

    print()
    print("=" * 70)
    print("LOADING TRAIN-ONLY SCALER")
    print("=" * 70)

    mean, std = load_train_scaler()

    # ========================================================
    # DATASETS
    # ========================================================

    print()
    print("=" * 70)
    print("LOADING PAIR MANIFESTS")
    print("=" * 70)

    train_dataset = SiamesePairDataset(
        TRAIN_PAIR_FILE,
        mean,
        std
    )

    validation_dataset = SiamesePairDataset(
        VALIDATION_PAIR_FILE,
        mean,
        std
    )

    test_dataset = SiamesePairDataset(
        TEST_PAIR_FILE,
        mean,
        std
    )

    print(
        f"Train pairs      : "
        f"{len(train_dataset):,}"
    )

    print(
        f"Validation pairs : "
        f"{len(validation_dataset):,}"
    )

    print(
        f"Test pairs       : "
        f"{len(test_dataset):,}"
    )

    # ========================================================
    # DATALOADERS
    # ========================================================

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available(),
    )

    validation_loader = DataLoader(
        validation_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available(),
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=torch.cuda.is_available(),
    )

    # ========================================================
    # MODEL
    # ========================================================

    print()
    print("=" * 70)
    print("BUILDING SIAMESE BiLSTM")
    print("=" * 70)

    model = SiameseBiLSTM().to(
        DEVICE
    )

    parameter_count = sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )

    print(
        f"Trainable parameters : "
        f"{parameter_count:,}"
    )

    # ========================================================
    # LOSS / OPTIMIZER
    # ========================================================

    criterion = ContrastiveLoss(
        margin=MARGIN
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=2,
    )

    # ========================================================
    # TRAINING
    # ========================================================

    print()
    print("=" * 70)
    print("TRAINING")
    print("=" * 70)

    best_validation_loss = float(
        "inf"
    )

    best_epoch = 0

    epochs_without_improvement = 0

    history = []

    best_model_path = (
        CHECKPOINT_DIR
        / "best_siamese_bilstm_v3.pt"
    )

    for epoch in range(
        1,
        EPOCHS + 1
    ):

        epoch_start = time.time()

        train_loss = train_one_epoch(
            model,
            train_loader,
            optimizer,
            criterion
        )

        validation_result = evaluate(
            model,
            validation_loader,
            criterion
        )

        validation_loss = (
            validation_result["loss"]
        )

        scheduler.step(
            validation_loss
        )

        current_lr = (
            optimizer.param_groups[0]["lr"]
        )

        elapsed = (
            time.time()
            - epoch_start
        )

        record = {
            "epoch": epoch,
            "train_loss": float(
                train_loss
            ),
            "validation_loss": float(
                validation_loss
            ),
            "learning_rate": float(
                current_lr
            ),
            "epoch_seconds": float(
                elapsed
            ),
        }

        history.append(
            record
        )

        print(
            f"Epoch {epoch:03d}/{EPOCHS} | "
            f"train_loss={train_loss:.6f} | "
            f"val_loss={validation_loss:.6f} | "
            f"lr={current_lr:.7f} | "
            f"time={elapsed:.1f}s"
        )

        # ----------------------------------------------------
        # BEST MODEL
        # ----------------------------------------------------

        if (
            validation_loss
            < best_validation_loss
        ):

            best_validation_loss = (
                validation_loss
            )

            best_epoch = epoch

            epochs_without_improvement = 0

            save_checkpoint(
                model,
                optimizer,
                epoch,
                validation_loss,
                best_model_path
            )

            print(
                "    -> NEW BEST MODEL SAVED"
            )

        else:

            epochs_without_improvement += 1

        # ----------------------------------------------------
        # EARLY STOPPING
        # ----------------------------------------------------

        if (
            epochs_without_improvement
            >= PATIENCE
        ):

            print()
            print(
                f"Early stopping after "
                f"{epoch} epochs."
            )

            break

    # ========================================================
    # SAVE HISTORY
    # ========================================================

    history_file = (
        REPORT_DIR
        / "training_history_v3.json"
    )

    with open(
        history_file,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            history,
            f,
            indent=4
        )

    # ========================================================
    # LOAD BEST MODEL
    # ========================================================

    print()
    print("=" * 70)
    print("LOADING BEST MODEL")
    print("=" * 70)

    checkpoint = torch.load(
        best_model_path,
        map_location=DEVICE
    )

    model.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )

    print(
        f"Best epoch : {best_epoch}"
    )

    print(
        f"Best validation loss : "
        f"{best_validation_loss:.6f}"
    )

    # ========================================================
    # VALIDATION THRESHOLD
    # ========================================================

    print()
    print("=" * 70)
    print("VALIDATION THRESHOLD SELECTION")
    print("=" * 70)

    validation_result = evaluate(
        model,
        validation_loader,
        criterion
    )

    validation_threshold = (
        find_best_validation_threshold(
            validation_result["distances"],
            validation_result["labels"]
        )
    )

    validation_eer = find_eer(
        validation_result["distances"],
        validation_result["labels"]
    )

    print(
        f"Validation threshold : "
        f"{validation_threshold['threshold']:.6f}"
    )

    print(
        f"Validation accuracy  : "
        f"{validation_threshold['accuracy']:.6f}"
    )

    print(
        f"Validation FAR       : "
        f"{validation_threshold['fpr']:.6f}"
    )

    print(
        f"Validation FRR       : "
        f"{validation_threshold['fnr']:.6f}"
    )

    print(
        f"Validation EER       : "
        f"{validation_eer['eer']:.6f}"
    )

    # ========================================================
    # FINAL TEST
    # ========================================================

    print()
    print("=" * 70)
    print("FINAL TEST EVALUATION")
    print("=" * 70)

    print(
        "IMPORTANT:"
    )

    print(
        "Test data is NOT used to select the threshold."
    )

    test_result = evaluate(
        model,
        test_loader,
        criterion,
        threshold=validation_threshold[
            "threshold"
        ]
    )

    test_metrics = (
        test_result["metrics"]
    )

    test_eer = find_eer(
        test_result["distances"],
        test_result["labels"]
    )

    print()
    print(
        f"Test threshold : "
        f"{validation_threshold['threshold']:.6f}"
    )

    print(
        f"Test accuracy  : "
        f"{test_metrics['accuracy']:.6f}"
    )

    print(
        f"Test FAR       : "
        f"{test_metrics['fpr']:.6f}"
    )

    print(
        f"Test FRR       : "
        f"{test_metrics['fnr']:.6f}"
    )

    print(
        f"Test TPR       : "
        f"{test_metrics['tpr']:.6f}"
    )

    print(
        f"Test EER       : "
        f"{test_eer['eer']:.6f}"
    )

    # ========================================================
    # SAVE METRICS
    # ========================================================

    metrics_summary = {

        "dataset": "AALTO_V3",

        "model": {
            "architecture":
                "Siamese BiLSTM",
            "sequence_length":
                SEQUENCE_LENGTH,
            "feature_count":
                FEATURE_COUNT,
            "hidden_size":
                LSTM_HIDDEN_SIZE,
            "lstm_layers":
                LSTM_LAYERS,
            "embedding_size":
                EMBEDDING_SIZE,
            "margin":
                MARGIN,
        },

        "training": {
            "seed": SEED,
            "batch_size":
                BATCH_SIZE,
            "learning_rate":
                LEARNING_RATE,
            "weight_decay":
                WEIGHT_DECAY,
            "epochs_completed":
                len(history),
            "best_epoch":
                best_epoch,
            "best_validation_loss":
                best_validation_loss,
        },

        "data": {
            "train_pairs":
                len(train_dataset),
            "validation_pairs":
                len(validation_dataset),
            "test_pairs":
                len(test_dataset),
        },

        "normalization": {
            "source":
                "TRAIN ONLY",
            "validation_used":
                False,
            "test_used":
                False,
        },

        "threshold": {
            "selected_from":
                "VALIDATION",
            "value":
                validation_threshold[
                    "threshold"
                ],
        },

        "validation": {
            "accuracy":
                validation_threshold[
                    "accuracy"
                ],
            "far":
                validation_threshold[
                    "fpr"
                ],
            "frr":
                validation_threshold[
                    "fnr"
                ],
            "eer":
                validation_eer[
                    "eer"
                ],
        },

        "test": {
            "accuracy":
                test_metrics[
                    "accuracy"
                ],
            "far":
                test_metrics[
                    "fpr"
                ],
            "frr":
                test_metrics[
                    "fnr"
                ],
            "tpr":
                test_metrics[
                    "tpr"
                ],
            "eer":
                test_eer[
                    "eer"
                ],
        },

        "research_controls": {
            "participant_level_split":
                True,
            "shared_siamese_weights":
                True,
            "model_performance_used_for_cohort":
                False,
            "validation_used_for_threshold":
                True,
            "test_used_for_threshold":
                False,
            "test_used_for_training":
                False,
            "train_only_normalization":
                True,
        },
    }

    metrics_file = (
        REPORT_DIR
        / "training_summary_v3.json"
    )

    with open(
        metrics_file,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            metrics_summary,
            f,
            indent=4
        )

    # ========================================================
    # FINAL
    # ========================================================

    total_time = (
        time.time()
        - start_time
    )

    print()
    print("=" * 70)
    print("SIAMESE BiLSTM V3 TRAINING COMPLETE")
    print("=" * 70)

    print()
    print(
        f"Best epoch             : "
        f"{best_epoch}"
    )

    print(
        f"Best validation loss   : "
        f"{best_validation_loss:.6f}"
    )

    print(
        f"Validation threshold   : "
        f"{validation_threshold['threshold']:.6f}"
    )

    print()
    print("FINAL TEST")
    print("-" * 70)

    print(
        f"Accuracy : "
        f"{test_metrics['accuracy']:.6f}"
    )

    print(
        f"FAR      : "
        f"{test_metrics['fpr']:.6f}"
    )

    print(
        f"FRR      : "
        f"{test_metrics['fnr']:.6f}"
    )

    print(
        f"TPR      : "
        f"{test_metrics['tpr']:.6f}"
    )

    print(
        f"EER      : "
        f"{test_eer['eer']:.6f}"
    )

    print()
    print("OUTPUTS")
    print("-" * 70)

    print(
        "Best model :",
        best_model_path
    )

    print(
        "History    :",
        history_file
    )

    print(
        "Summary    :",
        metrics_file
    )

    print()
    print(
        f"Processing time : "
        f"{total_time / 60:.2f} minutes"
    )

    print()
    print("=" * 70)
    print("RESEARCH CONTROLS")
    print("=" * 70)

    print(
        "Shared Siamese weights       : YES"
    )

    print(
        "Train-only normalization     : YES"
    )

    print(
        "Validation threshold        : YES"
    )

    print(
        "Test threshold tuning       : NO"
    )

    print(
        "Test used for training      : NO"
    )

    print(
        "Participant leakage         : NO"
    )

    print("=" * 70)


if __name__ == "__main__":
    main()